### ISSUE TITLE
Expose service for a specific domain on port 443

### ISSUE THREAD

**Issue by bokzor** [dokku/dokku-typesense#22]
Hi there,

I would like to expose a typesense service on port 443 for a specific domain.

This port is already being used by another dokku application with a different domain.

Is there a way to reach the typesense service with a custom domain on port 443?

Thanks for any feedback.

**Comment by josegonzalez** [comment]
You might wish to expose typesense via a service-proxy app. Some documentation on that is [here](https://github.com/dokku/service-proxy).

**Comment by bokzor** [comment]
Yes. Indeed. Seems a bit simpler than : https://dokku.com/docs/networking/network/#attaching-an-app-to-a-network
